### ISSUE TITLE
Erreurs possibles sur les valeurs des sidLength et sur le type des éléments de sidData

### ISSUE THREAD

**Issue by auraes** [farvardin/C64-music#1]
Les valeurs des sidLength semblent erronées, par exemple la valeur pour marche_hiver  est de 16400 au lieu de 25999.
Les éléments du tableau sidData[] sont bien de type unsiged char/byte/uint8_t mais en aucun cas des char (qui sur Arduino sont par défaut signés.)

**Comment by farvardin** [comment]
Bien vu, par contre le but de raccourcir le sidLength dans l'initialisation c'était pour « jeter » les données qui se trouvaient après, sinon ça bouclait mal l'extrait. De toute façon c'est juste une rapide démo.
Pour le "char", c'était comme ça dans le code d'origine des autres exemples. Ça fonctionne bien comme ça de toute façon.

**Comment by farvardin** [comment]
Les données s'étendent bien de -128 à +128 (par exemple : 8,-56,0,-33,-15,31,119,7,-96,8,65,8,-8,-63,44,96,5,65,8,121, -63,44,0,6,65,8,-56,0,-65,-15,31,71,6,-64,8,65,8,-8,49,28) donc ça me semble normal d'utiliser le type CHAR et pas autre chose, en tout cas surtout pas BYTE qui est limité de 0 à 255.

cf. https://www.arduino.cc/en/Reference/Char
