### ISSUE TITLE
Link to https://github.com/daitangio/sid-arduino-lib

### ISSUE THREAD

**Issue by daitangio** [farvardin/C64-music#3]
Hi, I am the Sid Arduino Lib maintainer:
https://github.com/daitangio/sid-arduino-lib

Can you link my repository to your Readme?

**Comment by farvardin** [comment]
Hello,

I'm sorry, I missed the notification for your issue entry!!

I've just done it! I'll have a closer look at your repo for sure!

**Comment by daitangio** [comment]
Thank you :)
